version: '3'
services:
  langchain-chainlit-chat-app:
    image: langchain-chainlit-chat-app:latest
    build: .
    ports:
      - "8005:8000"
    env_file:
      - .env
    working_dir: /app/
    command: ["chainlit", "run", "/app/main.py"]
