services:
  backend_db:
    env_file:
      - .env
    build:
      context: ./backend
    image: backend_db_img
    volumes:
      - ./backend:/usr/src/app/
    command: uvicorn main:app --host 0.0.0.0 --port 82
    ports:
      - "8000:82"
    networks:
      - app-network
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget","-q","--spider","http://localhost:82/health"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - UNIVSPIDER_URL=http://univspider:81
  
  weaviate:
    env_file:
      - .env
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./backend/weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    networks:
      - app-network
    environment:
      - OPENAI_APIKEY=$OPENAI_APIKEY
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - ENABLE_MODULES=text2vec-openai
      - CLUSTER_HOSTNAME=node1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 3s
      timeout: 5s
      retries: 5

  univspider:
    build:
      context: ./univspider
    image: univspider_img
    volumes:
      - ./univspider:/usr/src/app/
    command: python main.py
    ports:
      - "81:81"
    networks:
      - app-network

  langchain-chainlit-chat-app:
    depends_on:
      backend_db:
        condition: service_healthy
    image: langchain-chainlit-chat-app:latest
    build: ./langchain-chainlit-docker-deployment-template
    ports:
      - "666:8000"
    env_file:
      - .env
    working_dir: /home/appuser/app/
    command: ["chainlit", "run", "/home/appuser/app/demo_app/main.py"]
    networks:
      - app-network
    environment:
      - BACKEND_DB_URL=http://backend_db:82

networks:
  app-network:
    driver: bridge
